ALTER TABLE users
    ALTER COLUMN name TYPE VARCHAR(255),
    ALTER COLUMN email TYPE VARCHAR(255),
    ALTER COLUMN password_hash TYPE VARCHAR(255),
    ALTER COLUMN role TYPE VARCHAR(32),
    ALTER COLUMN status TYPE VARCHAR(32);
