package com.energy.marketplace.trade.domain.valueObject;

public enum TradeStateTransitionReasonCode {

    TRADE_CREATED,

    USER_VALIDATION_REQUESTED,
    USER_VALIDATION_SUCCEEDED,
    USER_VALIDATION_FAILED,

    LISTING_RESERVATION_REQUESTED,
    LISTING_RESERVED,
    LISTING_RESERVATION_FAILED,

    PAYMENT_AUTHORIZATION_REQUESTED,
    PAYMENT_AUTHORIZED,
    PAYMENT_AUTHORIZATION_FAILED,

    LISTING_CLOSE_REQUESTED,
    LISTING_CLOSED,
    LISTING_CLOSE_FAILED,

    PAYMENT_SETTLEMENT_REQUESTED,
    PAYMENT_SETTLED,
    PAYMENT_SETTLEMENT_FAILED,

    PAYMENT_ROLLBACK_SUCCEEDED,
    PAYMENT_ROLLBACK_FAILED,

    LISTING_COMPENSATION_SUCCEEDED,
    LISTING_COMPENSATION_FAILED,

    TRADE_COMPLETED,
    RECEIPT_JOB_REQUESTED,
    RECEIPT_GENERATED,
    RECEIPT_GENERATION_FAILED_RETRY_LATER
}
