"""create billing tables

Revision ID: 6044563c3ec4
Revises: 
Create Date: 2026-05-21 16:32:27.293488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6044563c3ec4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_currency', sa.String(length=3), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reserved_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('authorizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='authorization_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('amount_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.Integer(), nullable=False),
    sa.Column('amount_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='settlement_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['authorizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlements')
    op.drop_table('receipts')
    op.drop_table('authorizations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
