CREATE TABLE trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    status VARCHAR(64) NOT NULL,
    payment_authorization_id BIGINT,
    receipt_id BIGINT,
    CONSTRAINT pk_trades PRIMARY KEY (id)
);

CREATE TABLE trade_state_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trade_id BIGINT NOT NULL,
    from_status VARCHAR(64),
    to_status VARCHAR(64) NOT NULL,
    reason_code VARCHAR(128) NOT NULL,
    reason_details TEXT,
    changed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_trade_state_history PRIMARY KEY (id),
    CONSTRAINT fk_trade_state_history_trade FOREIGN KEY (trade_id) REFERENCES trades (id)
);
