ALTER TABLE trades
    ALTER COLUMN amount TYPE NUMERIC(19, 2),
    ALTER COLUMN currency_code TYPE VARCHAR(3),
    ALTER COLUMN status TYPE VARCHAR(64);

ALTER TABLE trade_state_history
    ALTER COLUMN from_status TYPE VARCHAR(64),
    ALTER COLUMN to_status TYPE VARCHAR(64),
    ALTER COLUMN reason_code TYPE VARCHAR(128),
    ALTER COLUMN changed_at TYPE TIMESTAMP WITHOUT TIME ZONE;
