package com.energy.marketplace.trade.domain.model;

public enum TradeStatus {

    CREATED,

    USER_VALIDATION_PENDING,
    USER_VALIDATED,

    LISTING_RESERVATION_PENDING,
    LISTING_RESERVED,

    PAYMENT_AUTHORIZATION_PENDING,
    PAYMENT_AUTHORIZED,

    LISTING_CLOSING_PENDING,
    LISTING_CLOSED,

    PAYMENT_SETTLEMENT_PENDING,
    PAYMENT_SETTLED,

    PAYMENT_ROLLBACK_PENDING,

    LISTING_COMPENSATION_PENDING,

    COMPLETED_RECEIPT_PENDING,
    RECEIPT_GENERATION_PENDING,

    COMPLETED,

    FAILED,
    COMPENSATION_FAILED
}
