spring:
  application:
    name: listing-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${LISTING_DB_URL:jdbc:postgresql://localhost:5432/listing_db}
    username: ${LISTING_DB_USERNAME:postgres}
    password: ${LISTING_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        missing-queues-fatal: false
        failed-declaration-retry-interval: 5000

listing:
  commands:
    queue: listing.commands.queue
  events:
    queue: listing.events.queue

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    root: INFO
    com.energy.marketplace: DEBUG

springdoc:
  api-docs:
    path: /listings/v3/api-docs
  swagger-ui:
    path: /listings/swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

